### ISSUE TITLE
Dossier throws a server error 

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/portal-web#161] opened 2022-02-21 15:55 UTC
**Describe the bug**
Server error occurs whenever you try to access the dossier. I don't rightly know what might be causing this. 

**To Reproduce**
1. Go to josa.ngo
2. Go to any dossier
3. See error

**Expected behavior**
Dossier should be accessed without errors.

**Screenshots**
![Screenshot 2022-02-21 at 17-51-16 Server error](https://user-images.githubusercontent.com/79845228/154988947-9f3fec3e-7fd0-493f-8397-d8bdeeacb21f.png)

**Comment by thread-koder** [comment] 2022-02-22 13:54
@alsahawneh Hello, hope you are having a nice day, could you please supply a link for a dossier, because I can't access the dossier so I can't reproduce the error, thank you.

**Comment by thread-koder** [comment] 2022-03-02 11:53
@alsahawneh Hello, Hope you are doing well, I will close this issue because this issue is related to a much bigger issue and you can find about it here #172, I'm working on the issue as we speak Also If you have any questions, please don't hesitate let me know.

**Closed by thread-koder** 2022-03-02 11:53 UTC
Labels: bug
